delete http://localhost:3001/api/upload/images/1604004491456-helikuparinen-marie-antoinette.jpg
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjVmMGRlNTJkMDViY2ExMzJlNDc1YTgyNSIsImlhdCI6MTU5NDc2ODM4OX0.nR9UMPBvskpmlI4J8QyYRIRmJ8vjwM2y1ni8jtYpSXw